apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hamayun-argocd
  namespace: default
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: hamayun-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
