apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-basic
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://github.com/hamayunahmad/hanatwest.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: hamayun-argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

