apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sts1
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sts1
  template:
    metadata:
      labels:
        app: sts1
    spec:
      containers:
      - image: mysql:9.2.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pass123"

